on: [push, workflow_dispatch]
jobs:
  cypress: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci # uruchom skrypty npm w srodowisku ciaglej integracji 
      - run: npx cypress run
      - run: npx cypress run --record
      - run: npx cypress cache clear
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
